name: Streamlit CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit Checks
        run: |
          streamlit hello  # Vérifie que Streamlit tourne sans erreur
